### ISSUE TITLE
Sync-Up March 2024

### ISSUE THREAD

**Issue by plehegar** [w3c/w3c-ietf-coord#2]
* Update robots.txt standards Community Group
   https://www.w3.org/community/robotstxt/

   we're not sure if this CG will go anywhere, but the topic is 
nevertheless interesting in the context of AI. I'm curious to know if 
this topic came up within IETF.

* Verifiable Credentials 2.0 went to CR last month, with the 
understanding the media type vc+jd+json is in good hands at IETF.

* The Solid Working Group charter is being sent back to the drawing 
board and we don't expect to approve in its current form. (Thanks to the 
W3C TAG for providing feedback).

* The proposed charter for the Federated Identity Working Group went out 
for review [2]. The coordination with OAuth seems to be happening properly.

* The proposed charter for the Web Application Security Working Group 
went out for review [3]. Among the new work, it contains work well-known 
URL for passkey endpoints and a HTTP response header field for 
"off-the-record".

* WebTransport (working well, please let them recharter),

* incremental font transfer (still waiting on updates).

* The second screen working group has some protocol work that might benefit from some more discussion.

* HAL JSON came across my desk this week (https://datatracker.ietf.org/doc/html/draft-kelly-json-hal) which seems likely to move ahead on the Independent Submissions track, which might inflame some of the more ornery JSON-LD people.

* WebRTC and RFC8865 

* IETF 119: we don't plan to send a W3C team there but we'll be at IETF 
120. In fact, I'm hoping I'll be able to be there as well as Simone.

**Comment by martinthomson** [comment]
Discussed WebRTC: conclusion was that the W3C can represent their understanding of things, including that RFC publication does not necessarily mean suitability for any purpose.  It varies, but an RFC needs to be proven in the market.

**Comment by martinthomson** [comment]
On robots.txt we discussed the need to merge efforts rather than contribute to the fracturing of the space between multiple efforts.  Work from some serious players (not all major stakeholders) is ongoing in the IETF, who published an RFC on robots.txt.  Expect some group to form at the IETF soon-ish.

**Comment by martinthomson** [comment]
Discussed: +flair and observed that https://datatracker.ietf.org/doc/html/draft-ietf-mediaman-suffixes-07 is nearing completion.

**Comment by martinthomson** [comment]
Discussed: compression dictionaries and this being in WICG (https://github.com/WICG/compression-dictionary-transport), but the work being duplicative of HTTP working group efforts.
